'use client';

import React, { useState } from 'react';
import type { Project, Client } from '@/lib/types/portal';
import {
  FileText,
  Printer,
  Copy,
  Check,
  X,
  Shield,
  Layers,
  CheckCircle2,
  DollarSign,
  Activity,
  Globe,
} from 'lucide-react';

interface ExecutiveBriefModalProps {
  isOpen: boolean;
  onClose: () => void;
  project: Project;
  client: Client | null;
}

export function ExecutiveBriefModal({
  isOpen,
  onClose,
  project,
  client,
}: ExecutiveBriefModalProps) {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const completedMilestones = project.milestones.filter((m) => m.status === 'completed');
  const activeMilestone = project.milestones[project.currentPhaseIndex] || project.milestones[0];
  const progressPercent = Math.round(
    (completedMilestones.length / (project.milestones.length || 1)) * 100
  );

  const totalDeliverables = project.milestones.reduce(
    (acc, m) => acc + (m.deliverables?.length || 0),
    0
  );
  const completedDeliverables = project.milestones.reduce(
    (acc, m) =>
      acc + (m.deliverables?.filter((d) => d.status === 'approved').length || 0),
    0
  );

  const handleCopyMarkdown = () => {
    const md = `# EXECUTIVE PROGRESS BRIEF: ${project.title}
**Date:** ${new Date().toLocaleDateString()}
**Client:** ${client?.name || 'Project Partner'} (${client?.company || 'Organization'})
**Overall Status:** ${project.status.toUpperCase()} (${progressPercent}% Sprinted)
**Active Phase:** Phase 0${activeMilestone.phaseNumber} - ${activeMilestone.title}

---

## 1. Executive Summary
${project.description}

## 2. Core Metrics
- **Contract Budget:** $${project.totalBudgetUsd.toLocaleString()} USD (₦${project.totalBudgetNgn.toLocaleString()} NGN)
- **Deliverables Shipped:** ${completedDeliverables} of ${totalDeliverables} items approved
- **Scope Baseline:** Genesis PRD v${project.prd.version} ${project.prd.signedOffAt ? '• SIGNED OFF' : '• PENDING SIGN-OFF'}
- **System Health:** 99.98% Edge Uptime • SSL Grade A+
- **Warranty:** ${project.warrantyDaysRemaining ?? 30} Days Active SLA Coverage

## 3. Sprint Phases
${project.milestones
  .map(
    (m) =>
      `- Phase 0${m.phaseNumber}: ${m.title} [Status: ${m.status.toUpperCase()}] ($${m.costUsd.toLocaleString()})`
  )
  .join('\n')}

---
*Generated by WebMuse OS Executive Cockpit*
`;

    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md overflow-y-auto">
      <div className="relative w-full max-w-3xl bg-zinc-950 border border-white/10 rounded-2xl shadow-2xl overflow-hidden font-mono my-8">
        {/* Header Bar */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-white/10 bg-white/[0.02]">
          <div className="flex items-center gap-2 text-cyan-400 text-xs font-bold uppercase tracking-wider">
            <FileText className="w-4 h-4" />
            <span>Executive Progress Brief &amp; Board Report</span>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopyMarkdown}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-white/10 hover:border-cyan-500/40 bg-white/[0.03] text-zinc-300 hover:text-white text-xs transition-colors"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied MD' : 'Copy MD'}</span>
            </button>

            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-cyan-500/30 hover:border-cyan-500 bg-cyan-500/10 text-cyan-300 text-xs transition-colors"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / PDF</span>
            </button>

            <button
              onClick={onClose}
              className="p-1.5 rounded-lg border border-white/10 hover:border-white/20 text-zinc-400 hover:text-white transition-colors"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Printable Brief Body */}
        <div className="p-6 sm:p-8 space-y-6 text-xs text-zinc-300 max-h-[75vh] overflow-y-auto">
          {/* Executive Overview Header */}
          <div className="border-b border-white/10 pb-6 space-y-2">
            <div className="flex items-center justify-between text-zinc-500 text-[11px]">
              <span>CONFIDENTIAL PARTNER BRIEF</span>
              <span>{new Date().toLocaleDateString(undefined, { dateStyle: 'full' })}</span>
            </div>
            <h2 className="text-2xl font-bold text-white tracking-tight font-display">
              {project.title}
            </h2>
            <p className="text-zinc-400 text-xs leading-relaxed font-sans">
              {project.description}
            </p>
            <div className="flex flex-wrap gap-4 pt-2 text-[11px] text-zinc-400">
              <div>
                <span className="text-zinc-500">Partner: </span>
                <span className="text-white font-semibold">{client?.name || 'Project Partner'}</span>
              </div>
              <div>
                <span className="text-zinc-500">Company: </span>
                <span className="text-white font-semibold">{client?.company || 'Organization'}</span>
              </div>
              <div>
                <span className="text-zinc-500">Scope Baseline: </span>
                <span className="text-cyan-400 font-semibold">Genesis PRD v{project.prd.version}</span>
              </div>
            </div>
          </div>

          {/* 4 Core Summary KPI Cards */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            <div className="p-3.5 rounded-xl bg-white/[0.02] border border-white/10 space-y-1">
              <span className="text-[10px] text-zinc-500 uppercase tracking-wider flex items-center gap-1">
                <Layers className="w-3 h-3 text-cyan-400" /> Progress
              </span>
              <div className="text-lg font-bold text-white">{progressPercent}%</div>
              <p className="text-[10px] text-cyan-400">Phase 0{activeMilestone.phaseNumber} Active</p>
            </div>

            <div className="p-3.5 rounded-xl bg-white/[0.02] border border-white/10 space-y-1">
              <span className="text-[10px] text-zinc-500 uppercase tracking-wider flex items-center gap-1">
                <DollarSign className="w-3 h-3 text-emerald-400" /> Contract
              </span>
              <div className="text-lg font-bold text-white">${project.totalBudgetUsd.toLocaleString()}</div>
              <p className="text-[10px] text-emerald-400">Escrow Protected</p>
            </div>

            <div className="p-3.5 rounded-xl bg-white/[0.02] border border-white/10 space-y-1">
              <span className="text-[10px] text-zinc-500 uppercase tracking-wider flex items-center gap-1">
                <CheckCircle2 className="w-3 h-3 text-purple-400" /> Deliverables
              </span>
              <div className="text-lg font-bold text-white">{completedDeliverables} / {totalDeliverables}</div>
              <p className="text-[10px] text-purple-300">Items Shipped</p>
            </div>

            <div className="p-3.5 rounded-xl bg-white/[0.02] border border-white/10 space-y-1">
              <span className="text-[10px] text-zinc-500 uppercase tracking-wider flex items-center gap-1">
                <Activity className="w-3 h-3 text-cyan-400" /> Uptime
              </span>
              <div className="text-lg font-bold text-emerald-400">99.98%</div>
              <p className="text-[10px] text-zinc-400">Grade A+ Security</p>
            </div>
          </div>

          {/* Phased Milestones Breakdown */}
          <div className="space-y-3">
            <h3 className="text-xs font-bold text-white uppercase tracking-wider flex items-center gap-2">
              <span>Phased Sprint Execution Matrix</span>
              <span className="text-zinc-500">({completedMilestones.length} of {project.milestones.length} Completed)</span>
            </h3>

            <div className="space-y-2">
              {project.milestones.map((m) => {
                const isCurrent = m.id === activeMilestone.id;
                const isDone = m.status === 'completed';
                return (
                  <div
                    key={m.id}
                    className={`p-3 rounded-xl border flex items-center justify-between gap-4 ${
                      isDone
                        ? 'bg-emerald-950/20 border-emerald-500/30 text-emerald-300'
                        : isCurrent
                        ? 'bg-cyan-950/20 border-cyan-500/40 text-cyan-200'
                        : 'bg-white/[0.01] border-white/5 text-zinc-400'
                    }`}
                  >
                    <div className="flex items-center gap-3">
                      <span className="w-6 h-6 rounded-full border border-current flex items-center justify-center text-[10px] font-bold">
                        0{m.phaseNumber}
                      </span>
                      <div>
                        <div className="font-bold text-white text-xs">{m.title}</div>
                        <div className="text-[10px] text-zinc-400 font-sans">
                          {m.deliverables?.length || 0} core deliverables • ~{m.targetCompletionDays} working days
                        </div>
                      </div>
                    </div>

                    <div className="text-right">
                      <div className="font-bold text-white">${m.costUsd.toLocaleString()}</div>
                      <span className="text-[10px] uppercase font-semibold">
                        {m.status.replace('_', ' ')}
                      </span>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Problem Statement & Architecture Summary */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2">
            <div className="p-4 rounded-xl bg-white/[0.02] border border-white/10 space-y-1.5">
              <span className="text-[10px] text-zinc-500 uppercase tracking-wider">Problem Statement</span>
              <p className="text-zinc-300 text-xs leading-relaxed font-sans">
                {project.prd.problemStatement}
              </p>
            </div>

            <div className="p-4 rounded-xl bg-white/[0.02] border border-white/10 space-y-1.5">
              <span className="text-[10px] text-zinc-500 uppercase tracking-wider">Core Architecture</span>
              <p className="text-zinc-300 text-xs leading-relaxed font-sans">
                {project.prd.coreArchitecture}
              </p>
            </div>
          </div>

          {/* Staging & Live Endpoints */}
          <div className="p-4 rounded-xl bg-cyan-950/20 border border-cyan-500/30 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
            <div>
              <span className="text-[10px] text-cyan-400 font-semibold uppercase tracking-wider flex items-center gap-1.5">
                <Globe className="w-3.5 h-3.5" /> Edge Staging Environment
              </span>
              <div className="text-white text-xs font-mono mt-0.5">
                {project.stagingUrl || 'https://staging.webmuse.dev/' + project.slug}
              </div>
            </div>
            <div className="text-right text-[11px] text-zinc-400">
              <div>SLA Warranty: <span className="text-emerald-400 font-bold">{project.warrantyDaysRemaining ?? 30} Days Remaining</span></div>
              <div className="text-[10px] text-zinc-500">24/7 Priority Hotline Active</div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-white/10 bg-white/[0.02] flex items-center justify-between text-[11px] text-zinc-500">
          <span>WebMuse OS • Executive Partnership Deck</span>
          <button
            onClick={onClose}
            className="px-4 py-1.5 rounded-lg bg-white/10 hover:bg-white/20 text-white font-semibold transition-colors"
          >
            Close Report
          </button>
        </div>
      </div>
    </div>
  );
}
