import { NextRequest, NextResponse } from 'next/server';
import { getProjectById } from '@/lib/server/store';

export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url);
    const projectId = searchParams.get('projectId');
    const asset = searchParams.get('asset') || 'brand_pack';

    const project = projectId ? await getProjectById(projectId) : null;
    const projectSlug = project?.slug || 'project';

    let filename = `${projectSlug}-brand-assets.zip`;
    let contentType = 'application/zip';
    let fileBody = `[WEBMUSE ASSET BUNDLE: ${projectSlug.toUpperCase()}]\nFormat: High-Res Vectors, SVG, PNG, EPS\nGenerated by WebMuse Operating System.`;

    if (asset === 'figma_master') {
      filename = `${projectSlug}-design-tokens-master.fig`;
      contentType = 'application/octet-stream';
      fileBody = `[WEBMUSE FIGMA MASTER TOKENS: ${projectSlug.toUpperCase()}]\nMaster components, color tokens, typography scales, responsive layouts.`;
    } else if (asset === 'playbook') {
      filename = `${projectSlug}-sla-deployment-playbook.pdf`;
      contentType = 'application/pdf';
      fileBody = `%PDF-1.4\n1 0 obj << /Title (WebMuse SLA Architecture Playbook) /Author (WebMuse) >> endobj\ntrailer << /Root 1 0 R >> %%EOF`;
    }

    return new NextResponse(fileBody, {
      status: 200,
      headers: {
        'Content-Type': contentType,
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    });
  } catch (error: any) {
    return NextResponse.json({ ok: false, error: error.message }, { status: 500 });
  }
}
