import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import {
  ArrowLeft,
  ArrowUpRight,
  ShieldCheck,
  HardHat,
  Layers,
  CheckCircle2,
  Lock,
  MapPin,
  AlertTriangle,
  Database,
  Cpu,
  FileCheck,
  Scale,
  Activity,
  Radio,
  Server,
  Zap,
  BookOpen,
} from "lucide-react";

export const metadata: Metadata = {
  title: "Seth HSE — Engineering an Enterprise Safety Operations System",
  description:
    "An in-depth engineering breakdown of Seth HSE: an enterprise health, safety, and environment platform for high-risk industrial environments — geofenced compliance, anti-spoof verification, dynamic safety protocols, and a 15-module strict modular monolith.",
};

const STACK_TABLE = [
  { layer: "Mobile App", tech: "Flutter 3.x · Dart", why: "Cross-platform Android & iOS field personnel client with offline-first geofence log queuing and native sensor bridges" },
  { layer: "Web Dashboard", tech: "Next.js 15 · React · Tailwind CSS", why: "Enterprise portal for real-time marshal dispatch maps, site audit trails, and compliance reports" },
  { layer: "Core Backend API", tech: "Node.js · Express · TypeScript (Strict)", why: "Modular monolith implementation adhering to 25 engineering fortress pillars" },
  { layer: "Datastore & Cache", tech: "PostgreSQL 16 · Prisma ORM · Redis", why: "Relational data model with Row-Level Security (RLS) org_id scoping, partial unique indices, and cache layer" },
  { layer: "Realtime & Location", tech: "Socket.IO · Google Maps API", why: "Live location telemetry streams, instant SOS escalation alerts, and boundary matching" },
  { layer: "Privacy & Compliance", tech: "NDPR + GDPR · Native DSAR · Audit Outbox", why: "Zero-trust RBAC, privacy-by-design, immutable audit log pipelines, and strict data residency controls" },
];

const MONOLITH_MODULES = [
  { module: "matching", purpose: "Algorithmic pairing of HSE Marshals to site personnel with DB-enforced single active match constraints." },
  { module: "safety-protocol", purpose: "Pre-job hazard checklists (e.g. Tower Climbing Protocols) with mandatory step-by-step verification." },
  { module: "attendance", purpose: "Geofenced check-in/check-out engine with anti-spoof validation and supervisor sign-off." },
  { module: "monitoring", purpose: "Real-time location pings, geofence radius evaluation, and inactive worker heartbeat monitoring." },
  { module: "audit & dsar", purpose: "Immutable event audit trails and automated Data Subject Access Rights export/deletion workflows." },
  { module: "iam & personnel", purpose: "Multi-tenant role-based access control, marshal jurisdiction resolution, and worker profiles." },
  { module: "reporting", purpose: "Structured field logs, incident reports, and offline-queued field updates." },
  { module: "learning (lms)", purpose: "Course enrollments, locked module progression, test attempts, and verified certificate generation." },
];

const ANTI_SPOOF_LAYERS = [
  { layer: "Layer 1", title: "Device Mock Location Guard", detail: "Rejects location payloads generated by Android developer options or fake GPS apps via native bridge checks." },
  { layer: "Layer 2", title: "Geofence Radius & Speed Check", detail: "Validates coordinate fixes against site boundaries and calculates physical velocity limits (>150 km/h threshold) to detect teleports." },
  { layer: "Layer 3", title: "NTP Server Time Sync", detail: "Ignores local device clocks, validating check-in timestamps strictly against server NTP synchronization." },
  { layer: "Layer 4", title: "Supervisor Photo & Biometric Proof", detail: "Requires site supervisor photo/biometric verification attached to high-risk task authorizations." },
];

const INVARIANTS = [
  {
    title: "Single Active Assignment",
    code: "CREATE UNIQUE INDEX uq_one_active_assignment ON assignments (personnel_id) WHERE status = 'active';",
    desc: "A field worker can only be actively assigned to one site at a time, strictly enforced in PostgreSQL schema.",
  },
  {
    title: "Single Open Shift",
    code: "CREATE UNIQUE INDEX uq_one_open_shift ON shifts (personnel_id) WHERE clock_out_at IS NULL;",
    desc: "Prevents double clock-ins across sites or overlapping shift records at the database level.",
  },
  {
    title: "Immutable Photo Capture Metadata",
    code: "CREATE TRIGGER trg_media_immutable BEFORE UPDATE ON media_uploads ... RAISE EXCEPTION 'Immutable';",
    desc: "Device GPS, timestamp, and device-key hash recorded at photo capture cannot be mutated post-insert.",
  },
  {
    title: "Transactional Outbox Pattern",
    code: "INSERT INTO outbox (event_type, payload) VALUES ($1, $2) -- executed in same DB transaction",
    desc: "Ensures domain events (e.g. ShiftStarted, IncidentReported) are never lost due to external broker network failure.",
  },
];

const METRICS = [
  { n: "15", l: "Bounded contexts" },
  { n: "0 ms", l: "Cross-module code imports" },
  { n: "1 active", l: "Match constraint per worker" },
  { n: "NDPR + GDPR", l: "Dual compliance posture" },
  { n: "4-tier", l: "Anti-spoof check-in verification" },
  { n: "100%", l: "Row-Level Security (RLS) org isolation" },
];

export default function SethHseCaseStudyPage() {
  return (
    <div className="flex flex-col min-h-screen bg-background text-foreground">
      {/* Header */}
      <header className="border-b border-card-border px-6 lg:px-24 py-6">
        <div className="max-w-4xl mx-auto flex items-center justify-between">
          <Link
            href="/"
            className="flex items-center gap-2.5 group focus-visible:outline focus-visible:outline-2 focus-visible:outline-electric-blue focus-visible:outline-offset-4 rounded-full"
          >
            <Image src="/webMuse-Logo.png" alt="WEBMUSE Logo" width={30} height={30} className="object-contain" />
            <span className="font-display font-bold tracking-widest text-base text-text-title">WEBMUSE</span>
          </Link>
          <Link
            href="/case-study"
            className="flex items-center gap-1.5 text-xs font-mono uppercase tracking-widest text-text-muted hover:text-foreground transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-electric-blue focus-visible:outline-offset-4 rounded"
          >
            <ArrowLeft className="h-3.5 w-3.5" />
            All case studies
          </Link>
        </div>
      </header>

      <main id="main-content" className="flex-grow relative overflow-hidden">
        <div
          className="absolute top-[5%] right-[-8%] h-[420px] w-[420px] rounded-full bg-mesh-purple opacity-25 blur-[140px] pointer-events-none"
          aria-hidden="true"
        />

        {/* Hero */}
        <section className="relative z-10 px-6 lg:px-24 pt-14 pb-10 md:pt-20 md:pb-14">
          <div className="max-w-4xl mx-auto">
            <span className="text-xs font-semibold tracking-widest text-electric-blue uppercase font-mono">
              Case Study · Seth HSE Platform
            </span>
            <h1 className="text-3xl md:text-5xl font-bold tracking-tight text-text-title mt-4 max-w-3xl">
              Engineering an Enterprise Safety Operations & Compliance System.
            </h1>
            <p className="text-text-muted font-light mt-5 text-base md:text-lg leading-relaxed max-w-2xl">
              Seth HSE is an enterprise-grade Health, Safety, and Environment (HSE) platform for high-risk
              industrial operations — telecom tower maintenance, oil & gas installations, and heavy construction —
              built on a strict 15-module monolith, database-enforced invariants, geofenced anti-spoof compliance,
              and an automated safety dispatch engine.
            </p>

            <div className="flex flex-wrap gap-2 mt-6">
              {[
                "15-Module Monolith",
                "Geofenced Compliance",
                "Anti-Spoof Verification",
                "Tower Climbing Protocol",
                "NDPR + GDPR Compliance",
                "Transactional Outbox",
              ].map((t) => (
                <span
                  key={t}
                  className="text-[10px] font-mono uppercase tracking-wider text-text-muted border border-card-border rounded-full px-2.5 py-1"
                >
                  {t}
                </span>
              ))}
            </div>
          </div>
        </section>

        <div className="max-w-4xl mx-auto px-6 lg:px-24 flex flex-col gap-16 pb-20">
          {/* Executive Overview */}
          <section>
            <span className="text-xs font-semibold uppercase font-mono text-text-muted tracking-wider">00 — Executive Summary</span>
            <h2 className="text-2xl md:text-3xl font-bold text-text-title tracking-tight mt-3">
              The Fortress Architecture: 25 Engineering Pillars.
            </h2>
            <p className="text-text-muted font-light mt-4 leading-relaxed">
              Before writing a line of production code, the Seth HSE platform was designed against a comprehensive
              25-Pillar Fortress Blueprint. In high-risk operations, a system failure isn&apos;t just a software bug — it is a
              physical safety liability. The architecture treats proof of presence, data privacy, and safety verification
              as hard system invariants rather than client-side promises.
            </p>
          </section>

          {/* Problem */}
          <section>
            <span className="text-xs font-semibold uppercase font-mono text-text-muted tracking-wider">01 — Problem</span>
            <h2 className="text-2xl md:text-3xl font-bold text-text-title tracking-tight mt-3">
              High-risk industrial work cannot rely on paper forms and unverified check-ins.
            </h2>
            <p className="text-text-muted font-light mt-4 leading-relaxed">
              In telecom infrastructure maintenance (such as 50-meter tower climbing) and heavy engineering sites across
              Nigeria and West Africa, safety compliance has historically suffered from systemic vulnerabilities:
            </p>
            <div className="grid gap-3 mt-6">
              {[
                {
                  k: "Location Fraud & Spoofing",
                  v: "Workers using GPS mock-location apps, modified OS builds, or proxy check-ins from miles away to claim attendance without stepping onto hazardous sites.",
                },
                {
                  k: "Protocol Bypass",
                  v: "Paper safety checklists signed after work is completed, bypassing mandatory pre-job hazard checks, PPE inspection, and site supervisor sign-offs.",
                },
                {
                  k: "Audit & Liability Failure",
                  v: "Disjointed WhatsApp groups and spreadsheets making regulatory compliance audits (NDPR/GDPR and industrial HSE regulations) unprovable during incident investigations.",
                },
                {
                  k: "Uncoordinated Dispatch",
                  v: "No real-time matching between certified HSE Marshals and active field personnel based on geographical proximity, skills, and site jurisdiction.",
                },
              ].map((row) => (
                <div key={row.k} className="glassmorphism-card rounded-xl p-5 flex gap-4">
                  <span className="text-[10px] font-mono uppercase tracking-widest text-electric-blue shrink-0 pt-0.5 w-32 font-semibold">
                    {row.k}
                  </span>
                  <p className="text-sm text-text-muted font-light leading-relaxed m-0">{row.v}</p>
                </div>
              ))}
            </div>
          </section>

          {/* Software Architecture */}
          <section>
            <span className="text-xs font-semibold uppercase font-mono text-text-muted tracking-wider">02 — Architecture</span>
            <h2 className="text-2xl md:text-3xl font-bold text-text-title tracking-tight mt-3">
              The 15-Module Modular Monolith & Boundary Guardrails.
            </h2>
            <p className="text-text-muted font-light mt-4 leading-relaxed">
              Seth HSE adopts a strict modular monolith pattern. Rather than deploying fragmented microservices that introduce
              network latency and distributed transaction complexity during Phase 1–3, the system is organized into 15 domain-bounded
              modules with strict build-time dependency isolation.
            </p>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-6">
              {MONOLITH_MODULES.map((m) => (
                <div key={m.module} className="glassmorphism-card rounded-xl p-5">
                  <div className="flex items-center gap-2">
                    <span className="h-2 w-2 rounded-full bg-electric-blue" />
                    <h3 className="text-base font-bold font-mono text-text-title tracking-tight">{m.module}</h3>
                  </div>
                  <p className="text-xs text-text-muted font-light mt-2 leading-relaxed">{m.purpose}</p>
                </div>
              ))}
            </div>

            <div className="glassmorphism-card rounded-xl p-6 mt-6">
              <h3 className="text-base font-bold text-text-title flex items-center gap-2">
                <Cpu className="h-4 w-4 text-electric-blue" />
                Build-Time Boundary Enforcement (`dependency-cruiser`)
              </h3>
              <p className="text-xs text-text-muted font-light mt-2 leading-relaxed">
                A module may only expose capabilities via its top-level <code className="px-1 py-0.5 rounded bg-card-border font-mono">index.ts</code>.
                Cross-module imports into internal <code className="px-1 py-0.5 rounded bg-card-border font-mono">domain/</code> or <code className="px-1 py-0.5 rounded bg-card-border font-mono">infrastructure/</code> directories fail CI instantly.
                Cross-context integration happens via narrow infrastructure-edge checkers (<code className="px-1 py-0.5 rounded bg-card-border font-mono">JurisdictionChecker</code>, <code className="px-1 py-0.5 rounded bg-card-border font-mono">MarshalMatchChecker</code>) or transactional outbox events.
              </p>
            </div>
          </section>

          {/* Database Invariants */}
          <section>
            <span className="text-xs font-semibold uppercase font-mono text-text-muted tracking-wider">03 — Data Integrity</span>
            <h2 className="text-2xl md:text-3xl font-bold text-text-title tracking-tight mt-3">
              Database Schema & Hard Invariants.
            </h2>
            <p className="text-text-muted font-light mt-4 leading-relaxed">
              Software rules can be accidentally bypassed in application code. Seth HSE embeds critical business invariants directly
              into the PostgreSQL relational engine:
            </p>

            <div className="grid gap-4 mt-6">
              {INVARIANTS.map((inv) => (
                <div key={inv.title} className="glassmorphism-card rounded-xl p-6">
                  <div className="flex items-center gap-2 text-electric-blue font-mono text-sm font-bold">
                    <Database className="h-4 w-4" />
                    {inv.title}
                  </div>
                  <pre className="mt-3 p-3 rounded-lg bg-card-border/40 text-xs font-mono text-emerald-400 overflow-x-auto">
                    {inv.code}
                  </pre>
                  <p className="text-xs text-text-muted font-light mt-3 leading-relaxed">{inv.desc}</p>
                </div>
              ))}
            </div>
          </section>

          {/* Core Mechanisms */}
          <section>
            <span className="text-xs font-semibold uppercase font-mono text-text-muted tracking-wider">04 — Domain Primitives</span>
            <h2 className="text-2xl md:text-3xl font-bold text-text-title tracking-tight mt-3">
              Core Engineering Primitives.
            </h2>
            <div className="grid gap-6 mt-6">
              <div className="glassmorphism-card rounded-xl p-6">
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-lg border bg-electric-blue/10 border-electric-blue/20 text-electric-blue">
                    <ShieldCheck className="h-5 w-5" />
                  </div>
                  <h3 className="text-lg font-bold text-text-title">Algorithmic Marshal-Personnel Dispatch</h3>
                </div>
                <p className="text-sm text-text-muted font-light mt-3 leading-relaxed">
                  Field personnel are paired with certified HSE Marshals in an active pairing model. The system executes real-time
                  jurisdiction checks comparing marshal site lists and regional geographic bounds against active workers.
                  When a worker moves between sites, the <code className="px-1 py-0.5 rounded bg-card-border font-mono text-xs">MarshalMatchChecker</code> adapter
                  atomically terminates old active matches and initializes new append-only match lifecycles.
                </p>
              </div>

              <div className="glassmorphism-card rounded-xl p-6">
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-lg border bg-electric-blue/10 border-electric-blue/20 text-electric-blue">
                    <HardHat className="h-5 w-5" />
                  </div>
                  <h3 className="text-lg font-bold text-text-title">Tower Climbing & High-Risk Safety Protocols</h3>
                </div>
                <p className="text-sm text-text-muted font-light mt-3 leading-relaxed">
                  Before high-risk tasks begin (such as telecom tower climbing), the platform mandates digital protocol executions.
                  The worker must perform mandatory step-by-step checks: Personal Protective Equipment (PPE) inspection (full-body harness, double lanyard with energy absorber, helmet),
                  site environmental/weather clearance, and dual digital sign-offs from both climber and supervisor before task activation.
                </p>
              </div>

              <div className="glassmorphism-card rounded-xl p-6">
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-lg border bg-electric-blue/10 border-electric-blue/20 text-electric-blue">
                    <Lock className="h-5 w-5" />
                  </div>
                  <h3 className="text-lg font-bold text-text-title">Dual Privacy Posture (NDPR + GDPR) & DSAR Engine</h3>
                </div>
                <p className="text-sm text-text-muted font-light mt-3 leading-relaxed">
                  Operating across Nigeria and European regions requires strict data privacy compliance. The <code className="px-1 py-0.5 rounded bg-card-border font-mono text-xs">dsar</code> module
                  implements native Data Subject Access Rights for automated profile export and right-to-be-forgotten deletion workflows.
                  Multi-tenancy isolation is enforced at the database layer via PostgreSQL Row-Level Security (RLS) policies tied to <code className="px-1 py-0.5 rounded bg-card-border font-mono text-xs">org_id</code>.
                </p>
              </div>
            </div>
          </section>

          {/* Anti-Spoofing */}
          <section>
            <span className="text-xs font-semibold uppercase font-mono text-text-muted tracking-wider">05 — Fraud Prevention</span>
            <h2 className="text-2xl md:text-3xl font-bold text-text-title tracking-tight mt-3">
              4-Tier Check-in Validation & Risk-Scoring Engine.
            </h2>
            <p className="text-text-muted font-light mt-4 leading-relaxed">
              Rather than trusting raw device claims, Seth HSE treats mobile location data as claims to be scored server-side.
              suspicious events are flagged for human supervisor review rather than triggering automatic account locks:
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mt-6">
              {ANTI_SPOOF_LAYERS.map((layer) => (
                <div key={layer.layer} className="glassmorphism-card rounded-xl p-5 flex flex-col justify-between">
                  <div>
                    <span className="text-[10px] font-mono uppercase tracking-widest text-electric-blue font-semibold">
                      {layer.layer}
                    </span>
                    <h3 className="text-base font-bold text-text-title tracking-tight mt-2">{layer.title}</h3>
                    <p className="text-xs text-text-muted font-light mt-2 leading-relaxed">{layer.detail}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* Tech Stack */}
          <section>
            <span className="text-xs font-semibold uppercase font-mono text-text-muted tracking-wider">06 — Technology Stack</span>
            <h2 className="text-2xl md:text-3xl font-bold text-text-title tracking-tight mt-3">
              Production Technology Stack & Architectural Rationale.
            </h2>
            <div className="mt-6 border border-card-border rounded-2xl overflow-hidden glassmorphism-card">
              <div className="overflow-x-auto">
                <table className="w-full text-left text-xs">
                  <thead className="bg-card-border/30 font-mono text-text-muted uppercase tracking-wider">
                    <tr>
                      <th className="p-4">Layer</th>
                      <th className="p-4">Technology</th>
                      <th className="p-4">Architectural Rationale</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-card-border/40 font-light">
                    {STACK_TABLE.map((row) => (
                      <tr key={row.layer} className="hover:bg-card-border/20 transition-colors">
                        <td className="p-4 font-mono font-semibold text-electric-blue">{row.layer}</td>
                        <td className="p-4 font-mono text-text-title">{row.tech}</td>
                        <td className="p-4 text-text-muted">{row.why}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </section>

          {/* Verified Metrics */}
          <section>
            <span className="text-xs font-semibold uppercase font-mono text-text-muted tracking-wider">07 — System Metrics</span>
            <h2 className="text-2xl md:text-3xl font-bold text-text-title tracking-tight mt-3">
              Verified Codebase Metrics.
            </h2>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-4 mt-6">
              {METRICS.map((m) => (
                <div key={m.l} className="glassmorphism-card rounded-xl p-5 text-center">
                  <div className="text-2xl md:text-3xl font-bold text-electric-blue font-mono">{m.n}</div>
                  <div className="text-[10px] font-mono uppercase tracking-widest text-text-muted mt-1.5">{m.l}</div>
                </div>
              ))}
            </div>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-card-border px-6 lg:px-24 py-8">
        <div className="max-w-4xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <span className="text-[10px] font-mono text-text-muted uppercase tracking-wider">
            © {new Date().getFullYear()} WEBMUSE INC. ALL RIGHTS RESERVED.
          </span>
          <nav aria-label="Legal" className="flex items-center gap-4 text-[10px] font-mono text-text-muted uppercase tracking-widest">
            <Link href="/privacy" className="hover:text-foreground transition-colors">Privacy</Link>
            <Link href="/terms" className="hover:text-foreground transition-colors">Terms</Link>
            <Link href="/status" className="hover:text-foreground transition-colors">Status</Link>
          </nav>
        </div>
      </footer>
    </div>
  );
}
