import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { ArrowLeft, ArrowUpRight, ShieldCheck, HardHat, Layers, CheckCircle2, Lock, MapPin, AlertTriangle } from "lucide-react";

export const metadata: Metadata = {
  title: "Seth HSE — Engineering an Enterprise Safety Operations System",
  description:
    "How WEBMUSE engineered Seth HSE: an enterprise health, safety, and environment platform for high-risk industrial environments — geofenced compliance, anti-spoof verification, dynamic safety protocols, and a 15-module strict modular monolith.",
};

const STACK_TABLE = [
  { layer: "Mobile Client", tech: "Flutter · Dart", why: "Cross-platform Android & iOS field personnel app with offline-first geofence queuing and device sensor access" },
  { layer: "Web Dashboard", tech: "Next.js 15 · TypeScript · Tailwind CSS", why: "Enterprise administration, real-time marshal dispatch map, safety audit logs, and compliance reporting" },
  { layer: "Core API", tech: "Node.js · Express · TypeScript", why: "Strict modular monolith architecture adhering to 25 engineering fortress pillars" },
  { layer: "Datastore", tech: "PostgreSQL 16 · Prisma · Redis", why: "Relational data model with Row-Level Security (RLS) org_id scoping, partial unique indices, and cache layer" },
  { layer: "Realtime & Geo", tech: "Socket.IO · Google Maps API", why: "Live location telemetry, immediate SOS escalation alerts, and boundary matching" },
  { layer: "Compliance & Security", tech: "NDPR + GDPR · Native DSAR · Audit Engine", why: "Zero-trust RBAC, privacy-by-design, immutable audit log pipelines, and strict data residency controls" },
];

const MONOLITH_MODULES = [
  { module: "matching", purpose: "Algorithmic pairing of HSE Marshals to site personnel with DB-enforced single active match constraints." },
  { module: "safety-protocol", purpose: "Pre-job hazard checklists (e.g. Tower Climbing Protocols) with mandatory step-by-step verification." },
  { module: "attendance", purpose: "Geofenced check-in/check-out engine with anti-spoof validation and supervisor sign-off." },
  { module: "monitoring", purpose: "Real-time telemetry, location tracking, and inactive worker heartbeat monitoring." },
  { module: "audit & dsar", purpose: "Immutable event audit trails and automated Data Subject Access Rights export/deletion workflows." },
  { module: "iam & personnel", purpose: "Multi-tenant role-based access control, marshal jurisdiction resolution, and worker profiles." },
];

const ANTI_SPOOF_LAYERS = [
  { layer: "Layer 1", title: "Device Mock Location Guard", detail: "Rejects location payloads generated by Android developer options or fake GPS apps via native bridge checks." },
  { layer: "Layer 2", title: "Geofence Radius & Speed Check", detail: "Validates coordinate fixes against site boundaries and calculates physical velocity limits to detect teleports." },
  { layer: "Layer 3", title: "NTP Server Time Sync", detail: "Ignores local device clocks, validating check-in timestamps strictly against server NTP synchronization." },
  { layer: "Layer 4", title: "Supervisor Photo & Biometric Proof", detail: "Requires site supervisor photo/biometric verification attached to high-risk task authorizations." },
];

const METRICS = [
  { n: "15", l: "Bounded modules" },
  { n: "0 ms", l: "Cross-module code imports" },
  { n: "1 active", l: "Match constraint per worker" },
  { n: "NDPR + GDPR", l: "Dual compliance posture" },
  { n: "4-tier", l: "Anti-spoof check-in verification" },
  { n: "100%", l: "Row-Level Security (RLS) org isolation" },
];

export default function SethHseCaseStudyPage() {
  return (
    <div className="flex flex-col min-h-screen bg-background text-foreground">
      {/* Header */}
      <header className="border-b border-card-border px-6 lg:px-24 py-6">
        <div className="max-w-4xl mx-auto flex items-center justify-between">
          <Link
            href="/"
            className="flex items-center gap-2.5 group focus-visible:outline focus-visible:outline-2 focus-visible:outline-electric-blue focus-visible:outline-offset-4 rounded-full"
          >
            <Image src="/webMuse-Logo.png" alt="WEBMUSE Logo" width={30} height={30} className="object-contain" />
            <span className="font-display font-bold tracking-widest text-base text-text-title">WEBMUSE</span>
          </Link>
          <Link
            href="/case-study"
            className="flex items-center gap-1.5 text-xs font-mono uppercase tracking-widest text-text-muted hover:text-foreground transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-electric-blue focus-visible:outline-offset-4 rounded"
          >
            <ArrowLeft className="h-3.5 w-3.5" />
            All case studies
          </Link>
        </div>
      </header>

      <main id="main-content" className="flex-grow relative overflow-hidden">
        <div
          className="absolute top-[5%] right-[-8%] h-[420px] w-[420px] rounded-full bg-mesh-purple opacity-25 blur-[140px] pointer-events-none"
          aria-hidden="true"
        />

        {/* Hero */}
        <section className="relative z-10 px-6 lg:px-24 pt-14 pb-10 md:pt-20 md:pb-14">
          <div className="max-w-4xl mx-auto">
            <span className="text-xs font-semibold tracking-widest text-electric-blue uppercase font-mono">
              Case Study · Seth HSE
            </span>
            <h1 className="text-3xl md:text-5xl font-bold tracking-tight text-text-title mt-4 max-w-2xl">
              Engineering an Enterprise Safety Operations System.
            </h1>
            <p className="text-text-muted font-light mt-5 text-base md:text-lg leading-relaxed max-w-2xl">
              Seth HSE is an enterprise-grade Health, Safety, and Environment platform for high-risk
              industrial operations — telecom tower maintenance, oil & gas, and heavy construction — built
              on a strict 15-module monolith, geofenced anti-spoof compliance, and automated safety protocols.
            </p>

            <div className="flex flex-wrap gap-2 mt-6">
              {["15-Module Monolith", "Geofenced Compliance", "Anti-Spoof Verification", "Tower Climbing Safety Protocol", "NDPR + GDPR"].map((t) => (
                <span
                  key={t}
                  className="text-[10px] font-mono uppercase tracking-wider text-text-muted border border-card-border rounded-full px-2.5 py-1"
                >
                  {t}
                </span>
              ))}
            </div>
          </div>
        </section>

        <div className="max-w-4xl mx-auto px-6 lg:px-24 flex flex-col gap-16 pb-20">
          {/* Problem */}
          <section>
            <span className="text-xs font-semibold uppercase font-mono text-text-muted tracking-wider">01 — Problem</span>
            <h2 className="text-2xl md:text-3xl font-bold text-text-title tracking-tight mt-3">
              High-risk industrial work cannot rely on paper forms and trust-me check-ins.
            </h2>
            <p className="text-text-muted font-light mt-4 leading-relaxed">
              When field personnel ascend telecom towers or enter hazardous industrial zones, safety compliance
              is literally a life-or-death operational requirement. Existing solutions suffer from three fatal flaws:
            </p>
            <div className="grid gap-3 mt-6">
              {[
                { k: "Location Fraud", v: "Workers using GPS spoofing apps or proxy clock-ins from outside the site boundary, invalidating safety insurance coverage." },
                { k: "Protocol Bypass", v: "Paper-based safety checklists filled out after work finishes rather than enforcing step-by-step verification before high-risk activities commence." },
                { k: "Audit Failure", v: "Fragmented spreadsheets and WhatsApp updates making regulatory compliance audits (NDPR/GDPR & industrial HSE standards) impossible to verify." },
              ].map((row) => (
                <div key={row.k} className="glassmorphism-card rounded-xl p-5 flex gap-4">
                  <span className="text-[10px] font-mono uppercase tracking-widest text-electric-blue shrink-0 pt-0.5 w-24">
                    {row.k}
                  </span>
                  <p className="text-sm text-text-muted font-light leading-relaxed m-0">{row.v}</p>
                </div>
              ))}
            </div>
          </section>

          {/* Architecture */}
          <section>
            <span className="text-xs font-semibold uppercase font-mono text-text-muted tracking-wider">02 — Architecture</span>
            <h2 className="text-2xl md:text-3xl font-bold text-text-title tracking-tight mt-3">
              The 25 Fortress Pillars & Modular Monolith.
            </h2>
            <p className="text-text-muted font-light mt-4 leading-relaxed">
              Seth HSE is engineered as a strict modular monolith across 15 bounded contexts. Cross-module code
              imports are forbidden by build-time dependency analysis (`dependency-cruiser`). Cross-context interactions
              occur exclusively at the infrastructure edge behind narrow port adapters.
            </p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-6">
              {MONOLITH_MODULES.map((m) => (
                <div key={m.module} className="glassmorphism-card rounded-xl p-5">
                  <div className="flex items-center gap-2">
                    <span className="h-2 w-2 rounded-full bg-electric-blue" />
                    <h3 className="text-base font-bold font-mono text-text-title tracking-tight">{m.module}</h3>
                  </div>
                  <p className="text-xs text-text-muted font-light mt-2 leading-relaxed">{m.purpose}</p>
                </div>
              ))}
            </div>
          </section>

          {/* Key Mechanisms */}
          <section>
            <span className="text-xs font-semibold uppercase font-mono text-text-muted tracking-wider">03 — Core Primitives</span>
            <h2 className="text-2xl md:text-3xl font-bold text-text-title tracking-tight mt-3">
              Verifiable engineering mechanisms in the Seth codebase.
            </h2>
            <div className="grid gap-6 mt-6">
              <div className="glassmorphism-card rounded-xl p-6">
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-lg border bg-electric-blue/10 border-electric-blue/20 text-electric-blue">
                    <ShieldCheck className="h-5 w-5" />
                  </div>
                  <h3 className="text-lg font-bold text-text-title">Algorithmic Marshal-Personnel Matching</h3>
                </div>
                <p className="text-sm text-text-muted font-light mt-3 leading-relaxed">
                  Field personnel are paired with certified HSE Marshals in an active pairing model. A worker has at
                  most one active match at a time, enforced directly in PostgreSQL via a partial unique index on
                  <code className="mx-1 px-1.5 py-0.5 rounded bg-card-border font-mono text-xs text-text-title">personnel_id WHERE ended_at IS NULL</code>.
                  Reassignments trigger automated end-of-match lifecycle hooks.
                </p>
              </div>

              <div className="glassmorphism-card rounded-xl p-6">
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-lg border bg-electric-blue/10 border-electric-blue/20 text-electric-blue">
                    <HardHat className="h-5 w-5" />
                  </div>
                  <h3 className="text-lg font-bold text-text-title">Tower Climbing & High-Risk Protocols</h3>
                </div>
                <p className="text-sm text-text-muted font-light mt-3 leading-relaxed">
                  Before high-risk tasks begin, the platform mandates step-by-step digital protocol executions.
                  For tower climbing, this includes PPE inspection (harness, fall arrester, helmet), site weather
                  clearance, and dual sign-off from both the climber and assigned HSE Marshal.
                </p>
              </div>

              <div className="glassmorphism-card rounded-xl p-6">
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-lg border bg-electric-blue/10 border-electric-blue/20 text-electric-blue">
                    <Lock className="h-5 w-5" />
                  </div>
                  <h3 className="text-lg font-bold text-text-title">Dual Compliance Posture (NDPR + GDPR)</h3>
                </div>
                <p className="text-sm text-text-muted font-light mt-3 leading-relaxed">
                  Because Seth HSE operates across West Africa and Europe, privacy is built into the architecture.
                  The <code className="mx-1 px-1.5 py-0.5 rounded bg-card-border font-mono text-xs text-text-title">dsar</code> module provides automated
                  Data Subject Access Rights (export and deletion), while PostgreSQL Row-Level Security (RLS) guarantees
                  tenant isolation by scoping queries strictly by <code className="mx-1 px-1.5 py-0.5 rounded bg-card-border font-mono text-xs text-text-title">org_id</code>.
                </p>
              </div>
            </div>
          </section>

          {/* Anti-Spoofing */}
          <section>
            <span className="text-xs font-semibold uppercase font-mono text-text-muted tracking-wider">04 — Anti-Spoof Engine</span>
            <h2 className="text-2xl md:text-3xl font-bold text-text-title tracking-tight mt-3">
              4-Tier Check-in Validation Pipeline.
            </h2>
            <p className="text-text-muted font-light mt-4 leading-relaxed">
              To eliminate false attendance and guarantee that safety marshals are physically present at work sites:
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mt-6">
              {ANTI_SPOOF_LAYERS.map((layer) => (
                <div key={layer.layer} className="glassmorphism-card rounded-xl p-5 flex flex-col justify-between">
                  <div>
                    <span className="text-[10px] font-mono uppercase tracking-widest text-electric-blue font-semibold">
                      {layer.layer}
                    </span>
                    <h3 className="text-base font-bold text-text-title tracking-tight mt-2">{layer.title}</h3>
                    <p className="text-xs text-text-muted font-light mt-2 leading-relaxed">{layer.detail}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* Stack Table */}
          <section>
            <span className="text-xs font-semibold uppercase font-mono text-text-muted tracking-wider">05 — Technology Stack</span>
            <h2 className="text-2xl md:text-3xl font-bold text-text-title tracking-tight mt-3">
              Production Stack & Technical Trade-offs.
            </h2>
            <div className="mt-6 border border-card-border rounded-2xl overflow-hidden glassmorphism-card">
              <div className="overflow-x-auto">
                <table className="w-full text-left text-xs">
                  <thead className="bg-card-border/30 font-mono text-text-muted uppercase tracking-wider">
                    <tr>
                      <th className="p-4">Layer</th>
                      <th className="p-4">Technology</th>
                      <th className="p-4">Architectural Rationale</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-card-border/40 font-light">
                    {STACK_TABLE.map((row) => (
                      <tr key={row.layer} className="hover:bg-card-border/20 transition-colors">
                        <td className="p-4 font-mono font-semibold text-electric-blue">{row.layer}</td>
                        <td className="p-4 font-mono text-text-title">{row.tech}</td>
                        <td className="p-4 text-text-muted">{row.why}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </section>

          {/* Metrics Grid */}
          <section>
            <span className="text-xs font-semibold uppercase font-mono text-text-muted tracking-wider">06 — Verified Metrics</span>
            <h2 className="text-2xl md:text-3xl font-bold text-text-title tracking-tight mt-3">
              Architecture numbers verified against code.
            </h2>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-4 mt-6">
              {METRICS.map((m) => (
                <div key={m.l} className="glassmorphism-card rounded-xl p-5 text-center">
                  <div className="text-2xl md:text-3xl font-bold text-electric-blue font-mono">{m.n}</div>
                  <div className="text-[10px] font-mono uppercase tracking-widest text-text-muted mt-1.5">{m.l}</div>
                </div>
              ))}
            </div>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-card-border px-6 lg:px-24 py-8">
        <div className="max-w-4xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <span className="text-[10px] font-mono text-text-muted uppercase tracking-wider">
            © {new Date().getFullYear()} WEBMUSE INC. ALL RIGHTS RESERVED.
          </span>
          <nav aria-label="Legal" className="flex items-center gap-4 text-[10px] font-mono text-text-muted uppercase tracking-widest">
            <Link href="/privacy" className="hover:text-foreground transition-colors">Privacy</Link>
            <Link href="/terms" className="hover:text-foreground transition-colors">Terms</Link>
            <Link href="/status" className="hover:text-foreground transition-colors">Status</Link>
          </nav>
        </div>
      </footer>
    </div>
  );
}
